// <auto-generated />
using Krishna.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Krishna.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230824094851_ProductTable")]
    partial class ProductTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Krishna.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "उपनिषद्",
                            Description = "ईशोपनिषद् शुक्ल यजुर्वेदीय शाखा के अन्तर्गत एक उपनिषद है। यह उपनिषद् अपने नन्हें कलेवर के कारण अन्य उपनिषदों के बीच बेहद महत्त्वपूर्ण स्थान रखता है। इसमें कोई कथा-कहानी नहीं है केवल आत्म वर्णन है। ",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "ईशोपनिषद्",
                            Price = 15.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "उपनिषद्",
                            Description = "कठ उपनिषद् या कठोपनिषद कृष्ण यजुर्वेदीय शाखा के अन्तर्गत एक उपनिषद है। 'कठ' नाम पाणिनि के अष्टाध्यायी में प्राप्त होता है। एक मुनिविशेष का भी नाम 'कठ' था। यह वेद की कठ शाखा के प्रवर्तक थे। पतंजलि के महाभाष्य के अनुसार कठ, वैशंपायन के शिष्य थे। ",
                            ImageUrl = "https://placehold.co/602x402",
                            Name = "कठोपनिषद",
                            Price = 13.99
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "पुराण",
                            Description = "दिव्य हिंदू त्रिमूर्ति के एक अंग, भगवान विष्णु अपने 10 अवतारों के माध्यम से गहरा आध्यात्मिक संदेश बताते हैं जो कई महाकाव्यों और किंवदंतियों का हिस्सा है।",
                            ImageUrl = "https://placehold.co/601x401",
                            Name = "विष्णु पुराण",
                            Price = 10.99
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "पुराण",
                            Description = "शिव पुराण सभी पुराणों में सर्वाधिक महत्त्वपूर्ण व सबसे ज्यादा पढ़ी जाने वाली पुराणों में से एक है। भगवान शिव के विविध रूपों, अवतारों, ज्योतिर्लिंगों, भक्तों और भक्ति का विशद् वर्णन किया गया है। इसमें शिव के कल्याणकारी स्वरूप का तात्त्विक विवेचन, रहस्य, महिमा और उपासना का विस्तृत वर्णन है। ।",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "शिव पुराण",
                            Price = 15.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
